// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHJ5x4rNDeoI6Hka-7W7CdJQOtVIGsZrQ',
    appId: '1:960350224846:web:fd2a3af79e3b896d5d6b9f',
    messagingSenderId: '960350224846',
    projectId: 'todoapp-c0ce2',
    authDomain: 'todoapp-c0ce2.firebaseapp.com',
    storageBucket: 'todoapp-c0ce2.appspot.com',
    measurementId: 'G-H5QR9MP90E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCpST92k-ARGfjlECTEcKz8jsbXQHEWZ0',
    appId: '1:960350224846:android:6f97737ffcadae2f5d6b9f',
    messagingSenderId: '960350224846',
    projectId: 'todoapp-c0ce2',
    storageBucket: 'todoapp-c0ce2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPJiTQFLlgLk09Urf4UgcVi7C5lq4ZA1E',
    appId: '1:960350224846:ios:4473d87a23b986415d6b9f',
    messagingSenderId: '960350224846',
    projectId: 'todoapp-c0ce2',
    storageBucket: 'todoapp-c0ce2.appspot.com',
    iosClientId: '960350224846-796ac7ul2siaaat12k67j1efhv0nsl3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPJiTQFLlgLk09Urf4UgcVi7C5lq4ZA1E',
    appId: '1:960350224846:ios:4473d87a23b986415d6b9f',
    messagingSenderId: '960350224846',
    projectId: 'todoapp-c0ce2',
    storageBucket: 'todoapp-c0ce2.appspot.com',
    iosClientId: '960350224846-796ac7ul2siaaat12k67j1efhv0nsl3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
